included:
  - BookCrit

excluded:
  - Pods
  - BookCrit/Utilities

line_length:
    warning: 150
    error: 400
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

